### ISSUE TITLE
Add documentation for training models from scratch

### ISSUE THREAD

**Issue by robertknight** [robertknight/ocrs-models#6]
I've been in Rust-land for a while working on the inference side of [ocrs](https://github.com/robertknight/ocrs/tree/main/ocrs).

This issue is a placeholder to repeat the process of training the detection / recognition models from scratch and write it up.

For reference, the last training runs for text recognition were captured on wandb at https://wandb.ai/robertknight/text-recognition.

I don't have metrics records for the text detection model's last training run, as I wasn't using wandb at that point, so a baseline will need to be established for that.

**Comment by Cyberboss** [comment]
Hi Robert,

I don't suppose you could point me to some tools for generating brand new or modifying the .jsonl files in the dataset?

I'm trying to use the text recognition model to parse a game's font from screenshots, but it's currently inaccurate.

**Comment by robertknight** [comment]
> I don't suppose you could point me to some tools for generating brand new or modifying the .jsonl files in the dataset?

The dataset comes from https://github.com/google-research-datasets/hiertext. That repository contains the .jsonl files but not the image annotation tools that were used to generate them. They might have been internal Google tools.

If look at the contents of the `.jsonl` files you can see that the format is fortunately not that complicated. The [`hiertext.py` file](https://github.com/robertknight/ocrs-models/blob/main/ocrs_models/datasets/hiertext.py#L240) in this repository contains the code used to read each entry and turn it into the tensors used as training targets.

If you are trying to train with a custom dataset, the main advice I have is to make sure you visualize items from the dataset after they are loaded and make sure they look similar to items from the original dataset. There is a tool in https://github.com/robertknight/ocrs-models/blob/main/ocrs_models/datasets/__main__.py which I used for visualizing the dataset originally.

**Comment by Cyberboss** [comment]
Thanks, ended up writing an annotating tool myself: https://github.com/Cyberboss/demon-bluff-deducer/tree/df1b725ecf2bd5c3aae55c8676506ce3b3455342/crates/training-data-generator
